---
kind: pipeline
name: pipeline-1

platform:
  os: linux
  arch: amd64

steps:
  - name: step-1
    image: alpine
    commands:
      - echo "Hello from pipeline-1"

trigger:
  ref:
    - refs/heads/main
    - refs/tags/**
    - refs/pull/**

---
kind: pipeline
name: pipeline-2

platform:
  os: linux
  arch: amd64

steps:
  - name: step-1
    image: alpine
    commands:
      - echo "Hello from pipeline-2"

trigger:
  ref:
    - refs/heads/main
    - refs/tags/**
    - refs/pull/**

depends_on:
  - pipeline-1
