---
kind: pipeline
name: pipeline-1

platform:
  os: linux
  arch: amd64

steps:
  - name: step-1
    image: alpine
    commands:
      - echo "Hello from pipeline-1ee"
trigger:
  event:
  - pull_request
  action:
  - opened
  - ready_for_review
