---
kind: pipeline
name: pipeline-1

platform:
  os: linux
  arch: amd64

steps:
  - name: step-1
    image: alpine
    commands:
      - echo "Hello from pipeline-11"
  - name: step-2
    image: alpine:3.16.0
    settings:
      repo: public.ecr.aws/micahhausler
      registry: public.ecr.aws
    commands:
      - echo "Hello from pipeline-22"
  - name: step-3
    image: alpine
    commands:
      - echo "Hello from pipeline-22"
    depends_on:
      - step-1
      - step-2
